export const sampleCategory = [
  {
    id: 4,
    name: "Carbon Capture and Storage",
    searchTerms: [
      "carbon capture and storage",
      "carbon capture utilisation",
      "CCUS",
      "carbon utlisation",
      "CCS",
      "direct air capture",
    ],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 5,
    name: "Climate Change and Sustainability",
    searchTerms: [
      "COP28",
      "UNFCCC",
      "climate change",
      "sustainability",
      "global warming",
      "greenhouse gas emissions",
      "CO2 Methane Emissions",
    ],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 52,
    name: "Coal",
    searchTerms: [
      "coal",
      "coal plant",
      "coal Mine",
      "coal Mine",
      "lignite",
      "steam coal",
      "thermal coal",
      "coal gasification",
    ],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 53,
    name: "Digital and Data",
    searchTerms: ["smart grid", "smart energy system", "AI and energy", "smart meter", "ai data centre"],
    showTable: true,
    links: [],
    articles: [
      {
        id: "0",
        link: "https://www.smart-energy.com/industry-sectors/smart-grid/solving-the-grids-ai-power-struggle-with-virtual-power-plants/",
        title: "Access Denied",
        summary: "Unable to fetch content due to access restrictions.",
        selected: false,
      },
      {
        id: "1",
        link: "https://www.siemens.com/uk/en/company/stories/industry-insider-focus-electrification-lessons-from-data-centres.html",
        title: "NOT AN ARTICLE",
        summary: "Content does not appear to be a summarizable article.",
        selected: false,
      },
      {
        id: "2",
        link: "https://hellofuture.orange.com/en/ai-boosts-the-need-for-agile-energy-solutions/",
        title: "AI boosts the need for agile energy solutions",
        summary:
          "The rise of generative AI has significantly increased energy consumption in data centers, with AI tools requiring ten times more power than standard Google searches. This surge in demand poses environmental challenges, including energy and water resource scarcity. Experts recommend optimizing cooling technologies, adopting smart grids, and utilizing energy storage systems to mitigate these issues. AI-driven data centers are expected to grow by 20% annually, intensifying pressure on energy infrastructure. Strategies like off-peak model training and local power generation integration are proposed to alleviate the strain on grids and improve sustainability.",
        selected: false,
      },
      {
        id: "3",
        link: "https://datacentremagazine.com/technology-and-ai/ge-vernova-unveils-energy-roadmap-to-power-trump-ai-plan",
        title: "Access Denied",
        summary: "Unable to fetch content due to access restrictions.",
        selected: false,
      },
      {
        id: "4",
        link: "http://www.worldbank.org/en/news/feature/2025/03/27/korea-inspires-green-digital-futures-for-afe-mozambique-and-madagascar",
        title: "Korea Inspires Green Digital Futures for Mozambique and Madagascar",
        summary:
          "Mozambique and Madagascar are leveraging Korea’s expertise in green digital technologies to balance digital transformation with sustainability. Delegations from both nations visited Korea to study AI-driven energy solutions, smart grids, and policy frameworks. Key initiatives include Mozambique’s projects on rural broadband and digital acceleration, and Madagascar’s focus on renewable energy and digital inclusion. Korea’s innovations, such as the Green Button Platform and Information Access Centers, are guiding efforts to optimize energy use and expand digital access. Supported by the Korea Digital Development program, both countries aim to build a greener, more inclusive digital future.",
        selected: false,
      },
      {
        id: "5",
        link: "https://utilityweek.co.uk/ai-and-opportunity-the-landscape-for-advanced-technology-and-utilities/",
        title: "Access Denied",
        summary: "Unable to fetch content due to access restrictions.",
        selected: false,
      },
      {
        id: "6",
        link: "https://www.smart-energy.com/industry-sectors/digitalisation/itron-partners-to-include-ai-and-genai-at-the-smart-grid-edge/",
        title: "Access Denied",
        summary: "Unable to fetch content due to access restrictions.",
        selected: false,
      },
      {
        id: "7",
        link: "https://www.itnews.asia/news/will-there-be-enough-power-to-sustain-the-growth-of-tech-driven-businesses-616066",
        title: "Will there be enough power to sustain the growth of tech-driven businesses?",
        summary:
          "The article examines the rising energy demands driven by AI, data centers, and electrification, highlighting challenges such as infrastructure constraints, supply chain bottlenecks, and government regulations. Industry leaders discuss strategies to improve energy efficiency, adopt renewable energy, and implement advanced cooling and power management technologies. Collaboration between governments, businesses, and ecosystem players is emphasized as critical to addressing shortages and ensuring sustainable growth. The article also explores innovations like liquid cooling, green hydrogen, and AI-driven energy optimization, alongside the importance of modernizing power grids and diversifying energy sources to meet future demands.",
        selected: false,
      },
      {
        id: "8",
        link: "https://www.businesswire.com/news/home/20250324192847/en/ETAP-and-Schneider-Electric-Unveil-Worlds-First-Digital-Twin-to-Simulate-AI-Factory-Power-Requirements-from-Grid-to-Chip-Level-Using-NVIDIA-Omniverse",
        title: "Access Denied",
        summary: "Unable to fetch content due to access restrictions.",
        selected: false,
      },
      {
        id: "9",
        link: "https://energydigital.com/technology-and-ai/ge-vernova-unveils-energy-roadmap-to-power-trump-ai-plan",
        title: "Access Denied",
        summary: "Unable to fetch content due to access restrictions.",
        selected: false,
      },
    ],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 10,
      fetchedCount: 4,
      errorCount: 6,
      currentArticle: null,
      isActive: false,
    },
    fetchedAllArticles: true,
    isFetchingNewArticles: false,
  },
  {
    id: 54,
    name: "Electricity, Energy Networks and Storage",
    searchTerms: ["battery Storage", "utility scale energy storage", "high voltage transmission", "redox flow"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 55,
    name: "Energy Efficiency / Management  ",
    searchTerms: ["energy efficiency", "energy management", "Demand side mangement"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 56,
    name: "Heat ",
    searchTerms: [
      "heat networks",
      "ground source heat pumps",
      "air source heat pumps",
      "waste heat recovery",
      "heat pump",
    ],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 57,
    name: "Health and Safety/Risk Management",
    searchTerms: ["energy health and safety", "energy HSSE", "energy HSE"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 58,
    name: "Hydrogen",
    searchTerms: ["hydrogen economy", "fuel cell", "blue hydrogen", "green hydrogen", "electrolysis"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 59,
    name: "Markets and Investment",
    searchTerms: ["investment in energy", "renewable financing", "sustainable financing", "energy finance"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 60,
    name: "Mergers & Acquisitions",
    searchTerms: ["energy acquistion", "energy takeover", "energy merger"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 61,
    name: "Nuclear Power",
    searchTerms: ["nuclear power", "nuclear", "fission", "fusion", "toxic waste"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 62,
    name: "Offshore Energy",
    searchTerms: ["offshore wind", "wave power", "tidal power", "offshore energy ", "offshore oil", "offshore gas"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 63,
    name: "Oil and Gas",
    searchTerms: [
      "oil and gas   ",
      "oil exploration",
      "upstream oil and gas",
      "exploration licence",
      "unconventional oil gas",
      "shale gas",
    ],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 64,
    name: "Policy",
    searchTerms: ["energy policy", "energy market reform", "energy strategy"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 65,
    name: "Renewables",
    searchTerms: [
      "windpower",
      "biomass",
      "solar PV",
      "concentrated solar",
      "wave tidal power",
      "hydropower",
      "windfarm solar farm",
    ],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 66,
    name: "Transport  ",
    searchTerms: ["electric vehicle", "PHEV", "biofuel"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 67,
    name: "Workforce",
    searchTerms: ["energy sector skills", "energy transition skills"],
    showTable: false,
    links: [],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
  {
    id: 73,
    name: "test",
    searchTerms: ["test1"],
    showTable: false,
    links: [
      {
        id: 97,
        url: "https://www.researchgate.net/figure/XCO2-retrieval-errors-from-MSR-d-synthetic-spectra-of-the-test1-for-the-global-ensemble_fig2_339270316",
        title: "",
      },
    ],
    articles: [],
    summary: "",
    articleFetchProgressProps: {
      totalArticles: 0,
      fetchedCount: 0,
      errorCount: 0,
      currentArticle: null,
      isActive: false,
    },
  },
];
